[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cyberguard-url-detection"
version = "0.1.0"
description = "AI-powered phishing and malware URL detection system."
authors = [{name = "Ayush Padaniya"}]
requires-python = ">=3.11"
dependencies = [
    # pip install -e . will look here, but it's okay to keep 
    # them in requirements-ci.txt for now to avoid duplication.
]

[tool.setuptools]
# This tells pip to look for your code in the root directory
package-dir = {"" = "."}